name: Test cache

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    strategy:
        matrix:
          board-name: [nucleo_f446re]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: uwam-workspace

      - name: Initialize
        working-directory: uwam-workspace
        run: |
          west init -l .
          west update -o=--depth=1 -n
      
      - name: Build Firmware
        working-directory: uwam-workspace
        run: |
          ls -a
          cd app
          west build -b nucleo_f446re