name: Test cache

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains

    strategy:
        matrix:
          target: [nucleo_f446re, nucleo_l412kb]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: uwam-workspace

      - name: Initialize
        working-directory: uwam-workspace
        run: |
          west init -l .
          west update
      
      - name: Build Firmware
        working-directory: uwam-workspace
        run: |
          cd app
          west build -b ${{ matrix.target }} -p
          mkdir -p out
          ls -a
          cp build/zephyr/zephyr.hex ./out/FW_V${{github.run_number}}-${{ matrix.target }}.hex || true

      - name: Archive Firmware
        uses: actions/upload-artifact@v3
        with:
          name: FW_ARTIFACTS-V${{github.run_number}}.zip
          path: uwam-workspace/app/out